// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CMS.Controllers
{
    public partial class TagsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TagsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Import()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SearchTag()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchTag);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetTag()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTag);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TagsController Actions { get { return MVC.CMS.Tags; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Tags";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Tags";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GridViewPartial = "GridViewPartial";
            public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            public readonly string ExportTo = "ExportTo";
            public readonly string Import = "Import";
            public readonly string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public readonly string SearchTag = "SearchTag";
            public readonly string GetTag = "GetTag";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GridViewPartial = "GridViewPartial";
            public const string SelectorGridViewPartial = "SelectorGridViewPartial";
            public const string ExportTo = "ExportTo";
            public const string Import = "Import";
            public const string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public const string SearchTag = "SearchTag";
            public const string GetTag = "GetTag";
        }


        static readonly ActionParamsClass_GridViewPartial s_params_GridViewPartial = new ActionParamsClass_GridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewPartial GridViewPartialParams { get { return s_params_GridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewPartial
        {
            public readonly string focusedRowIndex = "focusedRowIndex";
            public readonly string draggingIndex = "draggingIndex";
            public readonly string targetIndex = "targetIndex";
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_Import s_params_Import = new ActionParamsClass_Import();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Import ImportParams { get { return s_params_Import; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Import
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_GridViewBatchUpdatePartial s_params_GridViewBatchUpdatePartial = new ActionParamsClass_GridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewBatchUpdatePartial GridViewBatchUpdatePartialParams { get { return s_params_GridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
        }
        static readonly ActionParamsClass_SearchTag s_params_SearchTag = new ActionParamsClass_SearchTag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchTag SearchTagParams { get { return s_params_SearchTag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchTag
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetTag s_params_GetTag = new ActionParamsClass_GetTag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTag GetTagParams { get { return s_params_GetTag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTag
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GridViewPartial = "GridViewPartial";
                public readonly string Index = "Index";
                public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            }
            public readonly string GridViewPartial = "~/Areas/CMS/Views/Tags/GridViewPartial.cshtml";
            public readonly string Index = "~/Areas/CMS/Views/Tags/Index.cshtml";
            public readonly string SelectorGridViewPartial = "~/Areas/CMS/Views/Tags/SelectorGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TagsController : livemenu.Areas.CMS.Controllers.TagsController
    {
        public T4MVC_TagsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewPartial(int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "focusedRowIndex", focusedRowIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "draggingIndex", draggingIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "targetIndex", targetIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            GridViewPartialOverride(callInfo, focusedRowIndex, draggingIndex, targetIndex, command);
            return callInfo;
        }

        [NonAction]
        partial void SelectorGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelectorGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectorGridViewPartial);
            SelectorGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExportToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
            ExportToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ImportOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.JsonResult Import(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ImportOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void GridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<TagList, int> updateValues);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<TagList, int> updateValues)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            GridViewBatchUpdatePartialOverride(callInfo, updateValues);
            return callInfo;
        }

        [NonAction]
        partial void SearchTagOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult SearchTag(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchTag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SearchTagOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetTagOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetTag(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetTagOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
