// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CMS.Controllers
{
    public partial class PagesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PagesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ClearCacheOnSaveChanged()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClearCacheOnSaveChanged);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ClearPageCache()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClearPageCache);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RegeneratePage()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RegeneratePage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PagesController Actions { get { return MVC.CMS.Pages; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Pages";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Pages";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Internal = "Internal";
            public readonly string ClearCacheOnSaveChanged = "ClearCacheOnSaveChanged";
            public readonly string PagesCachingGridViewPartial = "PagesCachingGridViewPartial";
            public readonly string ClearAllCache = "ClearAllCache";
            public readonly string ClearPageCache = "ClearPageCache";
            public readonly string RegenerateAbsent = "RegenerateAbsent";
            public readonly string RegenerateAll = "RegenerateAll";
            public readonly string RegeneratePage = "RegeneratePage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Internal = "Internal";
            public const string ClearCacheOnSaveChanged = "ClearCacheOnSaveChanged";
            public const string PagesCachingGridViewPartial = "PagesCachingGridViewPartial";
            public const string ClearAllCache = "ClearAllCache";
            public const string ClearPageCache = "ClearPageCache";
            public const string RegenerateAbsent = "RegenerateAbsent";
            public const string RegenerateAll = "RegenerateAll";
            public const string RegeneratePage = "RegeneratePage";
        }


        static readonly ActionParamsClass_ClearCacheOnSaveChanged s_params_ClearCacheOnSaveChanged = new ActionParamsClass_ClearCacheOnSaveChanged();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClearCacheOnSaveChanged ClearCacheOnSaveChangedParams { get { return s_params_ClearCacheOnSaveChanged; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClearCacheOnSaveChanged
        {
            public readonly string value = "value";
        }
        static readonly ActionParamsClass_ClearPageCache s_params_ClearPageCache = new ActionParamsClass_ClearPageCache();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClearPageCache ClearPageCacheParams { get { return s_params_ClearPageCache; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClearPageCache
        {
            public readonly string id = "id";
            public readonly string fullCode = "fullCode";
        }
        static readonly ActionParamsClass_RegeneratePage s_params_RegeneratePage = new ActionParamsClass_RegeneratePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RegeneratePage RegeneratePageParams { get { return s_params_RegeneratePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RegeneratePage
        {
            public readonly string id = "id";
            public readonly string fullCode = "fullCode";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string PagesCachingGridViewPartial = "PagesCachingGridViewPartial";
            }
            public readonly string Index = "~/Areas/CMS/Views/Pages/Index.cshtml";
            public readonly string PagesCachingGridViewPartial = "~/Areas/CMS/Views/Pages/PagesCachingGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PagesController : livemenu.Areas.CMS.Controllers.PagesController
    {
        public T4MVC_PagesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InternalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Internal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Internal);
            InternalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClearCacheOnSaveChangedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, bool value);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClearCacheOnSaveChanged(bool value)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClearCacheOnSaveChanged);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "value", value);
            ClearCacheOnSaveChangedOverride(callInfo, value);
            return callInfo;
        }

        [NonAction]
        partial void PagesCachingGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PagesCachingGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagesCachingGridViewPartial);
            PagesCachingGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClearAllCacheOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClearAllCache()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClearAllCache);
            ClearAllCacheOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClearPageCacheOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id, string fullCode);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClearPageCache(long id, string fullCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClearPageCache);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fullCode", fullCode);
            ClearPageCacheOverride(callInfo, id, fullCode);
            return callInfo;
        }

        [NonAction]
        partial void RegenerateAbsentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult RegenerateAbsent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RegenerateAbsent);
            RegenerateAbsentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegenerateAllOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult RegenerateAll()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RegenerateAll);
            RegenerateAllOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegeneratePageOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id, string fullCode);

        [NonAction]
        public override System.Web.Mvc.JsonResult RegeneratePage(long id, string fullCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RegeneratePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fullCode", fullCode);
            RegeneratePageOverride(callInfo, id, fullCode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
