// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CMS.Controllers
{
    public partial class SEOController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SEOController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ImportMeta()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ImportMeta);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MetaGridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaGridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ImportSitemap()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ImportSitemap);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SitemapGridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitemapGridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveSitemapSettings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSitemapSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveRobotsSettings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveRobotsSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SEOController Actions { get { return MVC.CMS.SEO; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SEO";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SEO";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ImportMeta = "ImportMeta";
            public readonly string ExportMetaTo = "ExportMetaTo";
            public readonly string Meta = "Meta";
            public readonly string MetaGridViewPartial = "MetaGridViewPartial";
            public readonly string MetaGridViewBatchUpdatePartial = "MetaGridViewBatchUpdatePartial";
            public readonly string ImportSitemap = "ImportSitemap";
            public readonly string ExportSitemapTo = "ExportSitemapTo";
            public readonly string Sitemap = "Sitemap";
            public readonly string SitemapGridViewPartial = "SitemapGridViewPartial";
            public readonly string SitemapGridViewBatchUpdatePartial = "SitemapGridViewBatchUpdatePartial";
            public readonly string SitemapSettings = "SitemapSettings";
            public readonly string SaveSitemapSettings = "SaveSitemapSettings";
            public readonly string Robots = "Robots";
            public readonly string RobotsSettings = "RobotsSettings";
            public readonly string SaveRobotsSettings = "SaveRobotsSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ImportMeta = "ImportMeta";
            public const string ExportMetaTo = "ExportMetaTo";
            public const string Meta = "Meta";
            public const string MetaGridViewPartial = "MetaGridViewPartial";
            public const string MetaGridViewBatchUpdatePartial = "MetaGridViewBatchUpdatePartial";
            public const string ImportSitemap = "ImportSitemap";
            public const string ExportSitemapTo = "ExportSitemapTo";
            public const string Sitemap = "Sitemap";
            public const string SitemapGridViewPartial = "SitemapGridViewPartial";
            public const string SitemapGridViewBatchUpdatePartial = "SitemapGridViewBatchUpdatePartial";
            public const string SitemapSettings = "SitemapSettings";
            public const string SaveSitemapSettings = "SaveSitemapSettings";
            public const string Robots = "Robots";
            public const string RobotsSettings = "RobotsSettings";
            public const string SaveRobotsSettings = "SaveRobotsSettings";
        }


        static readonly ActionParamsClass_ImportMeta s_params_ImportMeta = new ActionParamsClass_ImportMeta();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ImportMeta ImportMetaParams { get { return s_params_ImportMeta; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ImportMeta
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_MetaGridViewBatchUpdatePartial s_params_MetaGridViewBatchUpdatePartial = new ActionParamsClass_MetaGridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MetaGridViewBatchUpdatePartial MetaGridViewBatchUpdatePartialParams { get { return s_params_MetaGridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MetaGridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
        }
        static readonly ActionParamsClass_ImportSitemap s_params_ImportSitemap = new ActionParamsClass_ImportSitemap();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ImportSitemap ImportSitemapParams { get { return s_params_ImportSitemap; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ImportSitemap
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_SitemapGridViewBatchUpdatePartial s_params_SitemapGridViewBatchUpdatePartial = new ActionParamsClass_SitemapGridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SitemapGridViewBatchUpdatePartial SitemapGridViewBatchUpdatePartialParams { get { return s_params_SitemapGridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SitemapGridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
        }
        static readonly ActionParamsClass_SaveSitemapSettings s_params_SaveSitemapSettings = new ActionParamsClass_SaveSitemapSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSitemapSettings SaveSitemapSettingsParams { get { return s_params_SaveSitemapSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSitemapSettings
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_SaveRobotsSettings s_params_SaveRobotsSettings = new ActionParamsClass_SaveRobotsSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveRobotsSettings SaveRobotsSettingsParams { get { return s_params_SaveRobotsSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveRobotsSettings
        {
            public readonly string settings = "settings";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Meta = "Meta";
                public readonly string MetaGridViewPartial = "MetaGridViewPartial";
                public readonly string Robots = "Robots";
                public readonly string RobotsSettings = "RobotsSettings";
                public readonly string RobotsSettingsInternalEdit = "RobotsSettingsInternalEdit";
                public readonly string Sitemap = "Sitemap";
                public readonly string SitemapGridViewPartial = "SitemapGridViewPartial";
                public readonly string SitemapSettings = "SitemapSettings";
                public readonly string SitemapSettingsInternalEdit = "SitemapSettingsInternalEdit";
            }
            public readonly string Meta = "~/Areas/CMS/Views/SEO/Meta.cshtml";
            public readonly string MetaGridViewPartial = "~/Areas/CMS/Views/SEO/MetaGridViewPartial.cshtml";
            public readonly string Robots = "~/Areas/CMS/Views/SEO/Robots.cshtml";
            public readonly string RobotsSettings = "~/Areas/CMS/Views/SEO/RobotsSettings.cshtml";
            public readonly string RobotsSettingsInternalEdit = "~/Areas/CMS/Views/SEO/RobotsSettingsInternalEdit.cshtml";
            public readonly string Sitemap = "~/Areas/CMS/Views/SEO/Sitemap.cshtml";
            public readonly string SitemapGridViewPartial = "~/Areas/CMS/Views/SEO/SitemapGridViewPartial.cshtml";
            public readonly string SitemapSettings = "~/Areas/CMS/Views/SEO/SitemapSettings.cshtml";
            public readonly string SitemapSettingsInternalEdit = "~/Areas/CMS/Views/SEO/SitemapSettingsInternalEdit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SEOController : livemenu.Areas.CMS.Controllers.SEOController
    {
        public T4MVC_SEOController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ImportMetaOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.JsonResult ImportMeta(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ImportMeta);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ImportMetaOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void ExportMetaToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportMetaTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportMetaTo);
            ExportMetaToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MetaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Meta()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Meta);
            MetaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MetaGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MetaGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaGridViewPartial);
            MetaGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MetaGridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<SEOPage, int> updateValues);

        [NonAction]
        public override System.Web.Mvc.ActionResult MetaGridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<SEOPage, int> updateValues)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MetaGridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            MetaGridViewBatchUpdatePartialOverride(callInfo, updateValues);
            return callInfo;
        }

        [NonAction]
        partial void ImportSitemapOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.JsonResult ImportSitemap(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ImportSitemap);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ImportSitemapOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void ExportSitemapToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportSitemapTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportSitemapTo);
            ExportSitemapToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SitemapOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Sitemap()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Sitemap);
            SitemapOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SitemapGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SitemapGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitemapGridViewPartial);
            SitemapGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SitemapGridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<SitemapPage, int> updateValues);

        [NonAction]
        public override System.Web.Mvc.ActionResult SitemapGridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<SitemapPage, int> updateValues)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitemapGridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            SitemapGridViewBatchUpdatePartialOverride(callInfo, updateValues);
            return callInfo;
        }

        [NonAction]
        partial void SitemapSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SitemapSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitemapSettings);
            SitemapSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveSitemapSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SitemapSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveSitemapSettings(SitemapSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSitemapSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            SaveSitemapSettingsOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void RobotsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Robots()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Robots);
            RobotsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RobotsSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RobotsSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RobotsSettings);
            RobotsSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveRobotsSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, RobotsSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveRobotsSettings(RobotsSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveRobotsSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            SaveRobotsSettingsOverride(callInfo, settings);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
