// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CMS.Controllers
{
    public partial class AttributesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AttributesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ComboBoxAttributesSelector()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComboBoxAttributesSelector);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditAddNewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditAddNewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditDeletePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDeletePartial);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AttributesController Actions { get { return MVC.CMS.Attributes; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Attributes";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Attributes";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ComboBoxAttributesSelector = "ComboBoxAttributesSelector";
            public readonly string EditPartial = "EditPartial";
            public readonly string EditAddNewPartial = "EditAddNewPartial";
            public readonly string EditUpdatePartial = "EditUpdatePartial";
            public readonly string EditDeletePartial = "EditDeletePartial";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ComboBoxAttributesSelector = "ComboBoxAttributesSelector";
            public const string EditPartial = "EditPartial";
            public const string EditAddNewPartial = "EditAddNewPartial";
            public const string EditUpdatePartial = "EditUpdatePartial";
            public const string EditDeletePartial = "EditDeletePartial";
        }


        static readonly ActionParamsClass_ComboBoxAttributesSelector s_params_ComboBoxAttributesSelector = new ActionParamsClass_ComboBoxAttributesSelector();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ComboBoxAttributesSelector ComboBoxAttributesSelectorParams { get { return s_params_ComboBoxAttributesSelector; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ComboBoxAttributesSelector
        {
            public readonly string uID = "uID";
            public readonly string agCode = "agCode";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditPartial s_params_EditPartial = new ActionParamsClass_EditPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPartial EditPartialParams { get { return s_params_EditPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPartial
        {
            public readonly string agCode = "agCode";
        }
        static readonly ActionParamsClass_EditAddNewPartial s_params_EditAddNewPartial = new ActionParamsClass_EditAddNewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditAddNewPartial EditAddNewPartialParams { get { return s_params_EditAddNewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditAddNewPartial
        {
            public readonly string attribute = "attribute";
            public readonly string agCode = "agCode";
        }
        static readonly ActionParamsClass_EditUpdatePartial s_params_EditUpdatePartial = new ActionParamsClass_EditUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUpdatePartial EditUpdatePartialParams { get { return s_params_EditUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUpdatePartial
        {
            public readonly string attribute = "attribute";
            public readonly string agCode = "agCode";
        }
        static readonly ActionParamsClass_EditDeletePartial s_params_EditDeletePartial = new ActionParamsClass_EditDeletePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDeletePartial EditDeletePartialParams { get { return s_params_EditDeletePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDeletePartial
        {
            public readonly string id = "id";
            public readonly string agCode = "agCode";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ComboBoxAttributesSelector = "ComboBoxAttributesSelector";
                public readonly string EditPartial = "EditPartial";
                public readonly string PopupPartial = "PopupPartial";
            }
            public readonly string ComboBoxAttributesSelector = "~/Areas/CMS/Views/Attributes/ComboBoxAttributesSelector.cshtml";
            public readonly string EditPartial = "~/Areas/CMS/Views/Attributes/EditPartial.cshtml";
            public readonly string PopupPartial = "~/Areas/CMS/Views/Attributes/PopupPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AttributesController : livemenu.Areas.CMS.Controllers.AttributesController
    {
        public T4MVC_AttributesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ComboBoxAttributesSelectorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string uID, string agCode, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ComboBoxAttributesSelector(string uID, string agCode, long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComboBoxAttributesSelector);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "uID", uID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agCode", agCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ComboBoxAttributesSelectorOverride(callInfo, uID, agCode, id);
            return callInfo;
        }

        [NonAction]
        partial void EditPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string agCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditPartial(string agCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agCode", agCode);
            EditPartialOverride(callInfo, agCode);
            return callInfo;
        }

        [NonAction]
        partial void EditAddNewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BWPAttribute attribute, string agCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditAddNewPartial(BWPAttribute attribute, string agCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditAddNewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "attribute", attribute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agCode", agCode);
            EditAddNewPartialOverride(callInfo, attribute, agCode);
            return callInfo;
        }

        [NonAction]
        partial void EditUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BWPAttribute attribute, string agCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditUpdatePartial(BWPAttribute attribute, string agCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "attribute", attribute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agCode", agCode);
            EditUpdatePartialOverride(callInfo, attribute, agCode);
            return callInfo;
        }

        [NonAction]
        partial void EditDeletePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string agCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditDeletePartial(int id, string agCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDeletePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agCode", agCode);
            EditDeletePartialOverride(callInfo, id, agCode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
