// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CRM.Controllers
{
    public partial class PriceListController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PriceListController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExportTo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewAddNewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewAddNewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewDeletePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewDeletePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Import()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetPriceListVersion()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPriceListVersion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CreatePriceListVersion()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CreatePriceListVersion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeletePriceListVersion()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeletePriceListVersion);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PriceListController Actions { get { return MVC.CRM.PriceList; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CRM";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PriceList";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PriceList";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GridViewPartial = "GridViewPartial";
            public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            public readonly string ExportTo = "ExportTo";
            public readonly string GridViewAddNewPartial = "GridViewAddNewPartial";
            public readonly string GridViewUpdatePartial = "GridViewUpdatePartial";
            public readonly string GridViewDeletePartial = "GridViewDeletePartial";
            public readonly string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public readonly string Import = "Import";
            public readonly string GetPriceListVersions = "GetPriceListVersions";
            public readonly string GetPriceListVersion = "GetPriceListVersion";
            public readonly string CreatePriceListVersion = "CreatePriceListVersion";
            public readonly string DeletePriceListVersion = "DeletePriceListVersion";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GridViewPartial = "GridViewPartial";
            public const string SelectorGridViewPartial = "SelectorGridViewPartial";
            public const string ExportTo = "ExportTo";
            public const string GridViewAddNewPartial = "GridViewAddNewPartial";
            public const string GridViewUpdatePartial = "GridViewUpdatePartial";
            public const string GridViewDeletePartial = "GridViewDeletePartial";
            public const string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public const string Import = "Import";
            public const string GetPriceListVersions = "GetPriceListVersions";
            public const string GetPriceListVersion = "GetPriceListVersion";
            public const string CreatePriceListVersion = "CreatePriceListVersion";
            public const string DeletePriceListVersion = "DeletePriceListVersion";
        }


        static readonly ActionParamsClass_GridViewPartial s_params_GridViewPartial = new ActionParamsClass_GridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewPartial GridViewPartialParams { get { return s_params_GridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewPartial
        {
            public readonly string focusedRowIndex = "focusedRowIndex";
            public readonly string draggingIndex = "draggingIndex";
            public readonly string targetIndex = "targetIndex";
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_SelectorGridViewPartial s_params_SelectorGridViewPartial = new ActionParamsClass_SelectorGridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SelectorGridViewPartial SelectorGridViewPartialParams { get { return s_params_SelectorGridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SelectorGridViewPartial
        {
            public readonly string isSingle = "isSingle";
        }
        static readonly ActionParamsClass_ExportTo s_params_ExportTo = new ActionParamsClass_ExportTo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExportTo ExportToParams { get { return s_params_ExportTo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExportTo
        {
            public readonly string PriceListVersionID = "PriceListVersionID";
        }
        static readonly ActionParamsClass_GridViewAddNewPartial s_params_GridViewAddNewPartial = new ActionParamsClass_GridViewAddNewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewAddNewPartial GridViewAddNewPartialParams { get { return s_params_GridViewAddNewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewAddNewPartial
        {
            public readonly string priceListElement = "priceListElement";
        }
        static readonly ActionParamsClass_GridViewUpdatePartial s_params_GridViewUpdatePartial = new ActionParamsClass_GridViewUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewUpdatePartial GridViewUpdatePartialParams { get { return s_params_GridViewUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewUpdatePartial
        {
            public readonly string priceListElement = "priceListElement";
        }
        static readonly ActionParamsClass_GridViewDeletePartial s_params_GridViewDeletePartial = new ActionParamsClass_GridViewDeletePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewDeletePartial GridViewDeletePartialParams { get { return s_params_GridViewDeletePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewDeletePartial
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GridViewBatchUpdatePartial s_params_GridViewBatchUpdatePartial = new ActionParamsClass_GridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewBatchUpdatePartial GridViewBatchUpdatePartialParams { get { return s_params_GridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
            public readonly string PriceListVersionID = "PriceListVersionID";
        }
        static readonly ActionParamsClass_Import s_params_Import = new ActionParamsClass_Import();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Import ImportParams { get { return s_params_Import; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Import
        {
            public readonly string file = "file";
            public readonly string PriceListVersionID = "PriceListVersionID";
        }
        static readonly ActionParamsClass_GetPriceListVersion s_params_GetPriceListVersion = new ActionParamsClass_GetPriceListVersion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPriceListVersion GetPriceListVersionParams { get { return s_params_GetPriceListVersion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPriceListVersion
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CreatePriceListVersion s_params_CreatePriceListVersion = new ActionParamsClass_CreatePriceListVersion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreatePriceListVersion CreatePriceListVersionParams { get { return s_params_CreatePriceListVersion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreatePriceListVersion
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_DeletePriceListVersion s_params_DeletePriceListVersion = new ActionParamsClass_DeletePriceListVersion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePriceListVersion DeletePriceListVersionParams { get { return s_params_DeletePriceListVersion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePriceListVersion
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string PriceListElementGridViewPartial = "PriceListElementGridViewPartial";
                public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            }
            public readonly string Index = "~/Areas/CRM/Views/PriceList/Index.cshtml";
            public readonly string PriceListElementGridViewPartial = "~/Areas/CRM/Views/PriceList/PriceListElementGridViewPartial.cshtml";
            public readonly string SelectorGridViewPartial = "~/Areas/CRM/Views/PriceList/SelectorGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PriceListController : livemenu.Areas.CRM.Controllers.PriceListController
    {
        public T4MVC_PriceListController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewPartial(int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "focusedRowIndex", focusedRowIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "draggingIndex", draggingIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "targetIndex", targetIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            GridViewPartialOverride(callInfo, focusedRowIndex, draggingIndex, targetIndex, command);
            return callInfo;
        }

        [NonAction]
        partial void SelectorGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool isSingle);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelectorGridViewPartial(bool isSingle)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectorGridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isSingle", isSingle);
            SelectorGridViewPartialOverride(callInfo, isSingle);
            return callInfo;
        }

        [NonAction]
        partial void ExportToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long PriceListVersionID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportTo(long PriceListVersionID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PriceListVersionID", PriceListVersionID);
            ExportToOverride(callInfo, PriceListVersionID);
            return callInfo;
        }

        [NonAction]
        partial void GridViewAddNewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PriceListElement priceListElement);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewAddNewPartial(PriceListElement priceListElement)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewAddNewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "priceListElement", priceListElement);
            GridViewAddNewPartialOverride(callInfo, priceListElement);
            return callInfo;
        }

        [NonAction]
        partial void GridViewUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PriceListElement priceListElement);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewUpdatePartial(PriceListElement priceListElement)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "priceListElement", priceListElement);
            GridViewUpdatePartialOverride(callInfo, priceListElement);
            return callInfo;
        }

        [NonAction]
        partial void GridViewDeletePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewDeletePartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewDeletePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GridViewDeletePartialOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<PriceListElement, int> updateValues, long PriceListVersionID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<PriceListElement, int> updateValues, long PriceListVersionID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PriceListVersionID", PriceListVersionID);
            GridViewBatchUpdatePartialOverride(callInfo, updateValues, PriceListVersionID);
            return callInfo;
        }

        [NonAction]
        partial void ImportOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string file, long PriceListVersionID);

        [NonAction]
        public override System.Web.Mvc.JsonResult Import(string file, long PriceListVersionID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PriceListVersionID", PriceListVersionID);
            ImportOverride(callInfo, file, PriceListVersionID);
            return callInfo;
        }

        [NonAction]
        partial void GetPriceListVersionsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetPriceListVersions()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPriceListVersions);
            GetPriceListVersionsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetPriceListVersionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetPriceListVersion(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPriceListVersion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetPriceListVersionOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreatePriceListVersionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.JsonResult CreatePriceListVersion(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CreatePriceListVersion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            CreatePriceListVersionOverride(callInfo, name);
            return callInfo;
        }

        [NonAction]
        partial void DeletePriceListVersionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeletePriceListVersion(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeletePriceListVersion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeletePriceListVersionOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
