// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CRM.Controllers
{
    public partial class ClientsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ClientsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LegalPersonalityCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalPersonalityCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LegalPersonalityCardSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalPersonalityCardSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClientCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClientCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WithoutTypeCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WithoutTypeCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WithoutTypeCardSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WithoutTypeCardSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NaturalPersonCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NaturalPersonCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NaturalPersonCardSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NaturalPersonCardSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IndividualProprietorCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndividualProprietorCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IndividualProprietorCardSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndividualProprietorCardSave);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ClientsController Actions { get { return MVC.CRM.Clients; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CRM";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Clients";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Clients";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ClientListGridViewPartial = "ClientListGridViewPartial";
            public readonly string NaturalPersonGridViewPartial = "NaturalPersonGridViewPartial";
            public readonly string ExportTo = "ExportTo";
            public readonly string LegalPersonalityCard = "LegalPersonalityCard";
            public readonly string LegalPersonalityCardSave = "LegalPersonalityCardSave";
            public readonly string ClientCard = "ClientCard";
            public readonly string WithoutTypeCard = "WithoutTypeCard";
            public readonly string WithoutTypeCardSave = "WithoutTypeCardSave";
            public readonly string NaturalPersonCard = "NaturalPersonCard";
            public readonly string NaturalPersonCardSave = "NaturalPersonCardSave";
            public readonly string IndividualProprietorCard = "IndividualProprietorCard";
            public readonly string IndividualProprietorCardSave = "IndividualProprietorCardSave";
            public readonly string SelectorClientListGridViewPartial = "SelectorClientListGridViewPartial";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ClientListGridViewPartial = "ClientListGridViewPartial";
            public const string NaturalPersonGridViewPartial = "NaturalPersonGridViewPartial";
            public const string ExportTo = "ExportTo";
            public const string LegalPersonalityCard = "LegalPersonalityCard";
            public const string LegalPersonalityCardSave = "LegalPersonalityCardSave";
            public const string ClientCard = "ClientCard";
            public const string WithoutTypeCard = "WithoutTypeCard";
            public const string WithoutTypeCardSave = "WithoutTypeCardSave";
            public const string NaturalPersonCard = "NaturalPersonCard";
            public const string NaturalPersonCardSave = "NaturalPersonCardSave";
            public const string IndividualProprietorCard = "IndividualProprietorCard";
            public const string IndividualProprietorCardSave = "IndividualProprietorCardSave";
            public const string SelectorClientListGridViewPartial = "SelectorClientListGridViewPartial";
        }


        static readonly ActionParamsClass_LegalPersonalityCard s_params_LegalPersonalityCard = new ActionParamsClass_LegalPersonalityCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LegalPersonalityCard LegalPersonalityCardParams { get { return s_params_LegalPersonalityCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LegalPersonalityCard
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LegalPersonalityCardSave s_params_LegalPersonalityCardSave = new ActionParamsClass_LegalPersonalityCardSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LegalPersonalityCardSave LegalPersonalityCardSaveParams { get { return s_params_LegalPersonalityCardSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LegalPersonalityCardSave
        {
            public readonly string item = "item";
        }
        static readonly ActionParamsClass_ClientCard s_params_ClientCard = new ActionParamsClass_ClientCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClientCard ClientCardParams { get { return s_params_ClientCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClientCard
        {
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_WithoutTypeCard s_params_WithoutTypeCard = new ActionParamsClass_WithoutTypeCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WithoutTypeCard WithoutTypeCardParams { get { return s_params_WithoutTypeCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WithoutTypeCard
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_WithoutTypeCardSave s_params_WithoutTypeCardSave = new ActionParamsClass_WithoutTypeCardSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WithoutTypeCardSave WithoutTypeCardSaveParams { get { return s_params_WithoutTypeCardSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WithoutTypeCardSave
        {
            public readonly string item = "item";
        }
        static readonly ActionParamsClass_NaturalPersonCard s_params_NaturalPersonCard = new ActionParamsClass_NaturalPersonCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NaturalPersonCard NaturalPersonCardParams { get { return s_params_NaturalPersonCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NaturalPersonCard
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_NaturalPersonCardSave s_params_NaturalPersonCardSave = new ActionParamsClass_NaturalPersonCardSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NaturalPersonCardSave NaturalPersonCardSaveParams { get { return s_params_NaturalPersonCardSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NaturalPersonCardSave
        {
            public readonly string item = "item";
        }
        static readonly ActionParamsClass_IndividualProprietorCard s_params_IndividualProprietorCard = new ActionParamsClass_IndividualProprietorCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndividualProprietorCard IndividualProprietorCardParams { get { return s_params_IndividualProprietorCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndividualProprietorCard
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_IndividualProprietorCardSave s_params_IndividualProprietorCardSave = new ActionParamsClass_IndividualProprietorCardSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndividualProprietorCardSave IndividualProprietorCardSaveParams { get { return s_params_IndividualProprietorCardSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndividualProprietorCardSave
        {
            public readonly string item = "item";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ClientListGridViewPartial = "ClientListGridViewPartial";
                public readonly string Index = "Index";
                public readonly string IndividualProprietorCard = "IndividualProprietorCard";
                public readonly string IndividualProprietorCardLayout = "IndividualProprietorCardLayout";
                public readonly string LegalPersonalityCard = "LegalPersonalityCard";
                public readonly string LegalPersonalityCardLayout = "LegalPersonalityCardLayout";
                public readonly string NaturalPersonCard = "NaturalPersonCard";
                public readonly string NaturalPersonCardLayout = "NaturalPersonCardLayout";
                public readonly string NaturalPersonGridViewPartial = "NaturalPersonGridViewPartial";
                public readonly string SelectorClientListGridViewPartial = "SelectorClientListGridViewPartial";
                public readonly string WithoutTypeCard = "WithoutTypeCard";
                public readonly string WithoutTypeCardLayout = "WithoutTypeCardLayout";
            }
            public readonly string ClientListGridViewPartial = "~/Areas/CRM/Views/Clients/ClientListGridViewPartial.cshtml";
            public readonly string Index = "~/Areas/CRM/Views/Clients/Index.cshtml";
            public readonly string IndividualProprietorCard = "~/Areas/CRM/Views/Clients/IndividualProprietorCard.cshtml";
            public readonly string IndividualProprietorCardLayout = "~/Areas/CRM/Views/Clients/IndividualProprietorCardLayout.cshtml";
            public readonly string LegalPersonalityCard = "~/Areas/CRM/Views/Clients/LegalPersonalityCard.cshtml";
            public readonly string LegalPersonalityCardLayout = "~/Areas/CRM/Views/Clients/LegalPersonalityCardLayout.cshtml";
            public readonly string NaturalPersonCard = "~/Areas/CRM/Views/Clients/NaturalPersonCard.cshtml";
            public readonly string NaturalPersonCardLayout = "~/Areas/CRM/Views/Clients/NaturalPersonCardLayout.cshtml";
            public readonly string NaturalPersonGridViewPartial = "~/Areas/CRM/Views/Clients/NaturalPersonGridViewPartial.cshtml";
            public readonly string SelectorClientListGridViewPartial = "~/Areas/CRM/Views/Clients/SelectorClientListGridViewPartial.cshtml";
            public readonly string WithoutTypeCard = "~/Areas/CRM/Views/Clients/WithoutTypeCard.cshtml";
            public readonly string WithoutTypeCardLayout = "~/Areas/CRM/Views/Clients/WithoutTypeCardLayout.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ClientsController : livemenu.Areas.CRM.Controllers.ClientsController
    {
        public T4MVC_ClientsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClientListGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClientListGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClientListGridViewPartial);
            ClientListGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NaturalPersonGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NaturalPersonGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NaturalPersonGridViewPartial);
            NaturalPersonGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExportToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
            ExportToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LegalPersonalityCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult LegalPersonalityCard(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalPersonalityCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LegalPersonalityCardOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LegalPersonalityCardSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ClientLegalPersonality item);

        [NonAction]
        public override System.Web.Mvc.ActionResult LegalPersonalityCardSave(ClientLegalPersonality item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalPersonalityCardSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            LegalPersonalityCardSaveOverride(callInfo, item);
            return callInfo;
        }

        [NonAction]
        partial void ClientCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long type);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClientCard(long type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClientCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ClientCardOverride(callInfo, type);
            return callInfo;
        }

        [NonAction]
        partial void WithoutTypeCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult WithoutTypeCard(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WithoutTypeCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            WithoutTypeCardOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void WithoutTypeCardSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Client item);

        [NonAction]
        public override System.Web.Mvc.ActionResult WithoutTypeCardSave(Client item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WithoutTypeCardSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            WithoutTypeCardSaveOverride(callInfo, item);
            return callInfo;
        }

        [NonAction]
        partial void NaturalPersonCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult NaturalPersonCard(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NaturalPersonCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NaturalPersonCardOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void NaturalPersonCardSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ClientNaturalPerson item);

        [NonAction]
        public override System.Web.Mvc.ActionResult NaturalPersonCardSave(ClientNaturalPerson item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NaturalPersonCardSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            NaturalPersonCardSaveOverride(callInfo, item);
            return callInfo;
        }

        [NonAction]
        partial void IndividualProprietorCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndividualProprietorCard(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndividualProprietorCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndividualProprietorCardOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void IndividualProprietorCardSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ClientIndividualProprietor item);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndividualProprietorCardSave(ClientIndividualProprietor item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndividualProprietorCardSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            IndividualProprietorCardSaveOverride(callInfo, item);
            return callInfo;
        }

        [NonAction]
        partial void SelectorClientListGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelectorClientListGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectorClientListGridViewPartial);
            SelectorClientListGridViewPartialOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
