// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CRM.Controllers
{
    public partial class PaymentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PaymentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveRobokassaSettings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveRobokassaSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PaymentController Actions { get { return MVC.CRM.Payment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CRM";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Payment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Payment";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Robokassa = "Robokassa";
            public readonly string RobokassaSettings = "RobokassaSettings";
            public readonly string SaveRobokassaSettings = "SaveRobokassaSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Robokassa = "Robokassa";
            public const string RobokassaSettings = "RobokassaSettings";
            public const string SaveRobokassaSettings = "SaveRobokassaSettings";
        }


        static readonly ActionParamsClass_SaveRobokassaSettings s_params_SaveRobokassaSettings = new ActionParamsClass_SaveRobokassaSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveRobokassaSettings SaveRobokassaSettingsParams { get { return s_params_SaveRobokassaSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveRobokassaSettings
        {
            public readonly string settings = "settings";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Robokassa = "Robokassa";
                public readonly string RobokassaSettings = "RobokassaSettings";
                public readonly string RobokassaSettingsInternalEdit = "RobokassaSettingsInternalEdit";
            }
            public readonly string Robokassa = "~/Areas/CRM/Views/Payment/Robokassa.cshtml";
            public readonly string RobokassaSettings = "~/Areas/CRM/Views/Payment/RobokassaSettings.cshtml";
            public readonly string RobokassaSettingsInternalEdit = "~/Areas/CRM/Views/Payment/RobokassaSettingsInternalEdit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PaymentController : livemenu.Areas.CRM.Controllers.PaymentController
    {
        public T4MVC_PaymentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RobokassaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Robokassa()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Robokassa);
            RobokassaOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RobokassaSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RobokassaSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RobokassaSettings);
            RobokassaSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveRobokassaSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, RobokassaSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveRobokassaSettings(RobokassaSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveRobokassaSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            SaveRobokassaSettingsOverride(callInfo, settings);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
