// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.CRM.Controllers
{
    public partial class OrderController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected OrderController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewDeletePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewDeletePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Card()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Card);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CardSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CardSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OrderElementGridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderElementGridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddOrderElements()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOrderElements);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult OrderCreated()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.OrderCreated);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult OrderIncomeRecived()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.OrderIncomeRecived);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ClientActivationRequest()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientActivationRequest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ClientFourDigitActivationRequest()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientFourDigitActivationRequest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ClientForgotPassword()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientForgotPassword);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OrderController Actions { get { return MVC.CRM.Order; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CRM";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Order";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Order";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ExportTo = "ExportTo";
            public readonly string Index = "Index";
            public readonly string OrderGridViewPartial = "OrderGridViewPartial";
            public readonly string GridViewDeletePartial = "GridViewDeletePartial";
            public readonly string Card = "Card";
            public readonly string Test = "Test";
            public readonly string CardSave = "CardSave";
            public readonly string OrderElementGridViewPartial = "OrderElementGridViewPartial";
            public readonly string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public readonly string AddOrderElements = "AddOrderElements";
            public readonly string OrderCreated = "OrderCreated";
            public readonly string OrderIncomeRecived = "OrderIncomeRecived";
            public readonly string OrderIncomeRecivedTEST = "OrderIncomeRecivedTEST";
            public readonly string ClientActivationRequest = "ClientActivationRequest";
            public readonly string ClientFourDigitActivationRequest = "ClientFourDigitActivationRequest";
            public readonly string ClientForgotPassword = "ClientForgotPassword";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ExportTo = "ExportTo";
            public const string Index = "Index";
            public const string OrderGridViewPartial = "OrderGridViewPartial";
            public const string GridViewDeletePartial = "GridViewDeletePartial";
            public const string Card = "Card";
            public const string Test = "Test";
            public const string CardSave = "CardSave";
            public const string OrderElementGridViewPartial = "OrderElementGridViewPartial";
            public const string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public const string AddOrderElements = "AddOrderElements";
            public const string OrderCreated = "OrderCreated";
            public const string OrderIncomeRecived = "OrderIncomeRecived";
            public const string OrderIncomeRecivedTEST = "OrderIncomeRecivedTEST";
            public const string ClientActivationRequest = "ClientActivationRequest";
            public const string ClientFourDigitActivationRequest = "ClientFourDigitActivationRequest";
            public const string ClientForgotPassword = "ClientForgotPassword";
        }


        static readonly ActionParamsClass_GridViewDeletePartial s_params_GridViewDeletePartial = new ActionParamsClass_GridViewDeletePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewDeletePartial GridViewDeletePartialParams { get { return s_params_GridViewDeletePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewDeletePartial
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Card s_params_Card = new ActionParamsClass_Card();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Card CardParams { get { return s_params_Card; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Card
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CardSave s_params_CardSave = new ActionParamsClass_CardSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CardSave CardSaveParams { get { return s_params_CardSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CardSave
        {
            public readonly string item = "item";
        }
        static readonly ActionParamsClass_OrderElementGridViewPartial s_params_OrderElementGridViewPartial = new ActionParamsClass_OrderElementGridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrderElementGridViewPartial OrderElementGridViewPartialParams { get { return s_params_OrderElementGridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrderElementGridViewPartial
        {
            public readonly string id = "id";
            public readonly string focusedRowIndex = "focusedRowIndex";
            public readonly string draggingIndex = "draggingIndex";
            public readonly string targetIndex = "targetIndex";
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_GridViewBatchUpdatePartial s_params_GridViewBatchUpdatePartial = new ActionParamsClass_GridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewBatchUpdatePartial GridViewBatchUpdatePartialParams { get { return s_params_GridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
            public readonly string elementOrderID = "elementOrderID";
        }
        static readonly ActionParamsClass_AddOrderElements s_params_AddOrderElements = new ActionParamsClass_AddOrderElements();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddOrderElements AddOrderElementsParams { get { return s_params_AddOrderElements; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddOrderElements
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_OrderCreated s_params_OrderCreated = new ActionParamsClass_OrderCreated();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrderCreated OrderCreatedParams { get { return s_params_OrderCreated; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrderCreated
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_OrderIncomeRecived s_params_OrderIncomeRecived = new ActionParamsClass_OrderIncomeRecived();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrderIncomeRecived OrderIncomeRecivedParams { get { return s_params_OrderIncomeRecived; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrderIncomeRecived
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClientActivationRequest s_params_ClientActivationRequest = new ActionParamsClass_ClientActivationRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClientActivationRequest ClientActivationRequestParams { get { return s_params_ClientActivationRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClientActivationRequest
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClientFourDigitActivationRequest s_params_ClientFourDigitActivationRequest = new ActionParamsClass_ClientFourDigitActivationRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClientFourDigitActivationRequest ClientFourDigitActivationRequestParams { get { return s_params_ClientFourDigitActivationRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClientFourDigitActivationRequest
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ClientForgotPassword s_params_ClientForgotPassword = new ActionParamsClass_ClientForgotPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClientForgotPassword ClientForgotPasswordParams { get { return s_params_ClientForgotPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClientForgotPassword
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Card = "Card";
                public readonly string CardLayout = "CardLayout";
                public readonly string Index = "Index";
                public readonly string OrderElementGridViewPartial = "OrderElementGridViewPartial";
                public readonly string OrderGridViewPartial = "OrderGridViewPartial";
            }
            public readonly string Card = "~/Areas/CRM/Views/Order/Card.cshtml";
            public readonly string CardLayout = "~/Areas/CRM/Views/Order/CardLayout.cshtml";
            public readonly string Index = "~/Areas/CRM/Views/Order/Index.cshtml";
            public readonly string OrderElementGridViewPartial = "~/Areas/CRM/Views/Order/OrderElementGridViewPartial.cshtml";
            public readonly string OrderGridViewPartial = "~/Areas/CRM/Views/Order/OrderGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_OrderController : livemenu.Areas.CRM.Controllers.OrderController
    {
        public T4MVC_OrderController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ExportToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
            ExportToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrderGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OrderGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderGridViewPartial);
            OrderGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GridViewDeletePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewDeletePartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewDeletePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GridViewDeletePartialOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Card(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Card);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CardOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Test()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Test);
            TestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CardSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Order item);

        [NonAction]
        public override System.Web.Mvc.ActionResult CardSave(Order item)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CardSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "item", item);
            CardSaveOverride(callInfo, item);
            return callInfo;
        }

        [NonAction]
        partial void OrderElementGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id, int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command);

        [NonAction]
        public override System.Web.Mvc.ActionResult OrderElementGridViewPartial(long id, int? focusedRowIndex, int? draggingIndex, int? targetIndex, string command)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderElementGridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "focusedRowIndex", focusedRowIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "draggingIndex", draggingIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "targetIndex", targetIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "command", command);
            OrderElementGridViewPartialOverride(callInfo, id, focusedRowIndex, draggingIndex, targetIndex, command);
            return callInfo;
        }

        [NonAction]
        partial void GridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<OrderElement, int> updateValues, long elementOrderID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<OrderElement, int> updateValues, long elementOrderID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "elementOrderID", elementOrderID);
            GridViewBatchUpdatePartialOverride(callInfo, updateValues, elementOrderID);
            return callInfo;
        }

        [NonAction]
        partial void AddOrderElementsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, livemenu.Areas.CRM.Controllers.AddOrderElementsModel data);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddOrderElements(livemenu.Areas.CRM.Controllers.AddOrderElementsModel data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOrderElements);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            AddOrderElementsOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void OrderCreatedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult OrderCreated(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.OrderCreated);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            OrderCreatedOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void OrderIncomeRecivedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult OrderIncomeRecived(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.OrderIncomeRecived);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            OrderIncomeRecivedOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void OrderIncomeRecivedTESTOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult OrderIncomeRecivedTEST()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.OrderIncomeRecivedTEST);
            OrderIncomeRecivedTESTOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClientActivationRequestOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClientActivationRequest(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientActivationRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClientActivationRequestOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ClientFourDigitActivationRequestOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClientFourDigitActivationRequest(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientFourDigitActivationRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClientFourDigitActivationRequestOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ClientForgotPasswordOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ClientForgotPassword(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ClientForgotPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ClientForgotPasswordOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
