// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Controllers
{
    public partial class PositionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PositionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PositionsGridViewAddNewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewAddNewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PositionsGridViewUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PositionsGridViewDeletePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewDeletePartial);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PositionController Actions { get { return MVC.Position; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Position";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Position";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Internal = "Internal";
            public readonly string PositionsGridViewPartial = "PositionsGridViewPartial";
            public readonly string PositionsGridViewAddNewPartial = "PositionsGridViewAddNewPartial";
            public readonly string PositionsGridViewUpdatePartial = "PositionsGridViewUpdatePartial";
            public readonly string PositionsGridViewDeletePartial = "PositionsGridViewDeletePartial";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Internal = "Internal";
            public const string PositionsGridViewPartial = "PositionsGridViewPartial";
            public const string PositionsGridViewAddNewPartial = "PositionsGridViewAddNewPartial";
            public const string PositionsGridViewUpdatePartial = "PositionsGridViewUpdatePartial";
            public const string PositionsGridViewDeletePartial = "PositionsGridViewDeletePartial";
        }


        static readonly ActionParamsClass_PositionsGridViewAddNewPartial s_params_PositionsGridViewAddNewPartial = new ActionParamsClass_PositionsGridViewAddNewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PositionsGridViewAddNewPartial PositionsGridViewAddNewPartialParams { get { return s_params_PositionsGridViewAddNewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PositionsGridViewAddNewPartial
        {
            public readonly string position = "position";
        }
        static readonly ActionParamsClass_PositionsGridViewUpdatePartial s_params_PositionsGridViewUpdatePartial = new ActionParamsClass_PositionsGridViewUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PositionsGridViewUpdatePartial PositionsGridViewUpdatePartialParams { get { return s_params_PositionsGridViewUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PositionsGridViewUpdatePartial
        {
            public readonly string position = "position";
        }
        static readonly ActionParamsClass_PositionsGridViewDeletePartial s_params_PositionsGridViewDeletePartial = new ActionParamsClass_PositionsGridViewDeletePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PositionsGridViewDeletePartial PositionsGridViewDeletePartialParams { get { return s_params_PositionsGridViewDeletePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PositionsGridViewDeletePartial
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string PositionsGridViewPartial = "PositionsGridViewPartial";
            }
            public readonly string Index = "~/Views/Position/Index.cshtml";
            public readonly string PositionsGridViewPartial = "~/Views/Position/PositionsGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PositionController : livemenu.Controllers.PositionController
    {
        public T4MVC_PositionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InternalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Internal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Internal);
            InternalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PositionsGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PositionsGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewPartial);
            PositionsGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PositionsGridViewAddNewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Position position);

        [NonAction]
        public override System.Web.Mvc.ActionResult PositionsGridViewAddNewPartial(Position position)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewAddNewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "position", position);
            PositionsGridViewAddNewPartialOverride(callInfo, position);
            return callInfo;
        }

        [NonAction]
        partial void PositionsGridViewUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Position position);

        [NonAction]
        public override System.Web.Mvc.ActionResult PositionsGridViewUpdatePartial(Position position)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "position", position);
            PositionsGridViewUpdatePartialOverride(callInfo, position);
            return callInfo;
        }

        [NonAction]
        partial void PositionsGridViewDeletePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PositionsGridViewDeletePartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PositionsGridViewDeletePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PositionsGridViewDeletePartialOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
