// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Controllers
{
    public partial class RightsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RightsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Internal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Internal);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RightsDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RightsCatalogChanged()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsCatalogChanged);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RightsMenuGridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsMenuGridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SimpleRightsGridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimpleRightsGridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SimpleRightsChanged()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimpleRightsChanged);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RightsCatalogTreeListPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsCatalogTreeListPartial);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RightsController Actions { get { return MVC.Rights; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Rights";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Rights";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Internal = "Internal";
            public readonly string RightsDetail = "RightsDetail";
            public readonly string RightsCatalogChanged = "RightsCatalogChanged";
            public readonly string RightsCatalog = "RightsCatalog";
            public readonly string RightsMenuGridViewPartial = "RightsMenuGridViewPartial";
            public readonly string SimpleRightsGridViewPartial = "SimpleRightsGridViewPartial";
            public readonly string SimpleRightsChanged = "SimpleRightsChanged";
            public readonly string RightsCatalogTreeListPartial = "RightsCatalogTreeListPartial";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Internal = "Internal";
            public const string RightsDetail = "RightsDetail";
            public const string RightsCatalogChanged = "RightsCatalogChanged";
            public const string RightsCatalog = "RightsCatalog";
            public const string RightsMenuGridViewPartial = "RightsMenuGridViewPartial";
            public const string SimpleRightsGridViewPartial = "SimpleRightsGridViewPartial";
            public const string SimpleRightsChanged = "SimpleRightsChanged";
            public const string RightsCatalogTreeListPartial = "RightsCatalogTreeListPartial";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Internal s_params_Internal = new ActionParamsClass_Internal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Internal InternalParams { get { return s_params_Internal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Internal
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RightsDetail s_params_RightsDetail = new ActionParamsClass_RightsDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RightsDetail RightsDetailParams { get { return s_params_RightsDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RightsDetail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RightsCatalogChanged s_params_RightsCatalogChanged = new ActionParamsClass_RightsCatalogChanged();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RightsCatalogChanged RightsCatalogChangedParams { get { return s_params_RightsCatalogChanged; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RightsCatalogChanged
        {
            public readonly string cid = "cid";
            public readonly string rsid = "rsid";
            public readonly string type = "type";
            public readonly string value = "value";
        }
        static readonly ActionParamsClass_RightsMenuGridViewPartial s_params_RightsMenuGridViewPartial = new ActionParamsClass_RightsMenuGridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RightsMenuGridViewPartial RightsMenuGridViewPartialParams { get { return s_params_RightsMenuGridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RightsMenuGridViewPartial
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SimpleRightsGridViewPartial s_params_SimpleRightsGridViewPartial = new ActionParamsClass_SimpleRightsGridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SimpleRightsGridViewPartial SimpleRightsGridViewPartialParams { get { return s_params_SimpleRightsGridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SimpleRightsGridViewPartial
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SimpleRightsChanged s_params_SimpleRightsChanged = new ActionParamsClass_SimpleRightsChanged();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SimpleRightsChanged SimpleRightsChangedParams { get { return s_params_SimpleRightsChanged; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SimpleRightsChanged
        {
            public readonly string rsid = "rsid";
            public readonly string sid = "sid";
            public readonly string value = "value";
        }
        static readonly ActionParamsClass_RightsCatalogTreeListPartial s_params_RightsCatalogTreeListPartial = new ActionParamsClass_RightsCatalogTreeListPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RightsCatalogTreeListPartial RightsCatalogTreeListPartialParams { get { return s_params_RightsCatalogTreeListPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RightsCatalogTreeListPartial
        {
            public readonly string cid = "cid";
            public readonly string rsid = "rsid";
            public readonly string isRoot = "isRoot";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _RightsButtonsPanel = "_RightsButtonsPanel";
                public readonly string _RightsCatalogTreeListPartial = "_RightsCatalogTreeListPartial";
                public readonly string _RightsMenuGridViewPartial = "_RightsMenuGridViewPartial";
                public readonly string _SimpleRightsGridViewPartial = "_SimpleRightsGridViewPartial";
                public readonly string Index = "Index";
                public readonly string RightsCatalog = "RightsCatalog";
                public readonly string RightsDetail = "RightsDetail";
            }
            public readonly string _RightsButtonsPanel = "~/Views/Rights/_RightsButtonsPanel.cshtml";
            public readonly string _RightsCatalogTreeListPartial = "~/Views/Rights/_RightsCatalogTreeListPartial.cshtml";
            public readonly string _RightsMenuGridViewPartial = "~/Views/Rights/_RightsMenuGridViewPartial.cshtml";
            public readonly string _SimpleRightsGridViewPartial = "~/Views/Rights/_SimpleRightsGridViewPartial.cshtml";
            public readonly string Index = "~/Views/Rights/Index.cshtml";
            public readonly string RightsCatalog = "~/Views/Rights/RightsCatalog.cshtml";
            public readonly string RightsDetail = "~/Views/Rights/RightsDetail.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RightsController : livemenu.Controllers.RightsController
    {
        public T4MVC_RightsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndexOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void InternalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Internal(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Internal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InternalOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RightsDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RightsDetail(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RightsDetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RightsCatalogChangedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long cid, long rsid, int type, bool value);

        [NonAction]
        public override System.Web.Mvc.ActionResult RightsCatalogChanged(long cid, long rsid, int type, bool value)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsCatalogChanged);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cid", cid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rsid", rsid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "value", value);
            RightsCatalogChangedOverride(callInfo, cid, rsid, type, value);
            return callInfo;
        }

        [NonAction]
        partial void RightsCatalogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RightsCatalog()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsCatalog);
            RightsCatalogOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RightsMenuGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RightsMenuGridViewPartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsMenuGridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RightsMenuGridViewPartialOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SimpleRightsGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SimpleRightsGridViewPartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimpleRightsGridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SimpleRightsGridViewPartialOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SimpleRightsChangedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long rsid, int sid, bool value);

        [NonAction]
        public override System.Web.Mvc.ActionResult SimpleRightsChanged(long rsid, int sid, bool value)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimpleRightsChanged);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rsid", rsid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sid", sid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "value", value);
            SimpleRightsChangedOverride(callInfo, rsid, sid, value);
            return callInfo;
        }

        [NonAction]
        partial void RightsCatalogTreeListPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long cid, long rsid, bool isRoot);

        [NonAction]
        public override System.Web.Mvc.ActionResult RightsCatalogTreeListPartial(long cid, long rsid, bool isRoot)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RightsCatalogTreeListPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cid", cid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rsid", rsid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isRoot", isRoot);
            RightsCatalogTreeListPartialOverride(callInfo, cid, rsid, isRoot);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
