// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.Settings.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ApplicationStateChanged()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ApplicationStateChanged);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoginPageSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoginPageSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveCatalogSettings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveCatalogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Settings.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Settings";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Menu = "Menu";
            public readonly string LoginPage = "LoginPage";
            public readonly string Applications = "Applications";
            public readonly string ApplicationStateChanged = "ApplicationStateChanged";
            public readonly string LoginPageSave = "LoginPageSave";
            public readonly string Internal = "Internal";
            public readonly string Catalog = "Catalog";
            public readonly string CatalogSettings = "CatalogSettings";
            public readonly string SaveCatalogSettings = "SaveCatalogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Menu = "Menu";
            public const string LoginPage = "LoginPage";
            public const string Applications = "Applications";
            public const string ApplicationStateChanged = "ApplicationStateChanged";
            public const string LoginPageSave = "LoginPageSave";
            public const string Internal = "Internal";
            public const string Catalog = "Catalog";
            public const string CatalogSettings = "CatalogSettings";
            public const string SaveCatalogSettings = "SaveCatalogSettings";
        }


        static readonly ActionParamsClass_ApplicationStateChanged s_params_ApplicationStateChanged = new ActionParamsClass_ApplicationStateChanged();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ApplicationStateChanged ApplicationStateChangedParams { get { return s_params_ApplicationStateChanged; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ApplicationStateChanged
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_LoginPageSave s_params_LoginPageSave = new ActionParamsClass_LoginPageSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoginPageSave LoginPageSaveParams { get { return s_params_LoginPageSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoginPageSave
        {
            public readonly string applicationSettings = "applicationSettings";
        }
        static readonly ActionParamsClass_SaveCatalogSettings s_params_SaveCatalogSettings = new ActionParamsClass_SaveCatalogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveCatalogSettings SaveCatalogSettingsParams { get { return s_params_SaveCatalogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveCatalogSettings
        {
            public readonly string settings = "settings";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Applications = "Applications";
                public readonly string Catalog = "Catalog";
                public readonly string CatalogSettings = "CatalogSettings";
                public readonly string CatalogSettingsInternalEdit = "CatalogSettingsInternalEdit";
                public readonly string Index = "Index";
                public readonly string LoginPage = "LoginPage";
                public readonly string LoginPageInternal = "LoginPageInternal";
                public readonly string LoginPageInternalEdit = "LoginPageInternalEdit";
                public readonly string Menu = "Menu";
            }
            public readonly string Applications = "~/Areas/Settings/Views/Home/Applications.cshtml";
            public readonly string Catalog = "~/Areas/Settings/Views/Home/Catalog.cshtml";
            public readonly string CatalogSettings = "~/Areas/Settings/Views/Home/CatalogSettings.cshtml";
            public readonly string CatalogSettingsInternalEdit = "~/Areas/Settings/Views/Home/CatalogSettingsInternalEdit.cshtml";
            public readonly string Index = "~/Areas/Settings/Views/Home/Index.cshtml";
            public readonly string LoginPage = "~/Areas/Settings/Views/Home/LoginPage.cshtml";
            public readonly string LoginPageInternal = "~/Areas/Settings/Views/Home/LoginPageInternal.cshtml";
            public readonly string LoginPageInternalEdit = "~/Areas/Settings/Views/Home/LoginPageInternalEdit.cshtml";
            public readonly string Menu = "~/Areas/Settings/Views/Home/Menu.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : livemenu.Areas.Settings.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Menu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Menu);
            MenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoginPageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoginPage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoginPage);
            LoginPageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ApplicationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Applications()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Applications);
            ApplicationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ApplicationStateChangedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, ApplicationStateModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult ApplicationStateChanged(ApplicationStateModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ApplicationStateChanged);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ApplicationStateChangedOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void LoginPageSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ApplicationSettings applicationSettings);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoginPageSave(ApplicationSettings applicationSettings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoginPageSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "applicationSettings", applicationSettings);
            LoginPageSaveOverride(callInfo, applicationSettings);
            return callInfo;
        }

        [NonAction]
        partial void InternalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Internal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Internal);
            InternalOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CatalogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Catalog()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Catalog);
            CatalogOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CatalogSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CatalogSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CatalogSettings);
            CatalogSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveCatalogSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, CatalogSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveCatalogSettings(CatalogSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveCatalogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            SaveCatalogSettingsOverride(callInfo, settings);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
