// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.WMS.Controllers
{
    public partial class AddressesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AddressesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Import()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SearchAddress()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchAddress);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetAddress()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAddress);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AddressesController Actions { get { return MVC.WMS.Addresses; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "WMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Addresses";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Addresses";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            public readonly string Import = "Import";
            public readonly string ExportTo = "ExportTo";
            public readonly string GridViewPartial = "GridViewPartial";
            public readonly string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public readonly string SearchAddress = "SearchAddress";
            public readonly string GetAddress = "GetAddress";
            public readonly string UpdateAddressCoords = "UpdateAddressCoords";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SelectorGridViewPartial = "SelectorGridViewPartial";
            public const string Import = "Import";
            public const string ExportTo = "ExportTo";
            public const string GridViewPartial = "GridViewPartial";
            public const string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public const string SearchAddress = "SearchAddress";
            public const string GetAddress = "GetAddress";
            public const string UpdateAddressCoords = "UpdateAddressCoords";
        }


        static readonly ActionParamsClass_Import s_params_Import = new ActionParamsClass_Import();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Import ImportParams { get { return s_params_Import; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Import
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_GridViewBatchUpdatePartial s_params_GridViewBatchUpdatePartial = new ActionParamsClass_GridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewBatchUpdatePartial GridViewBatchUpdatePartialParams { get { return s_params_GridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
        }
        static readonly ActionParamsClass_SearchAddress s_params_SearchAddress = new ActionParamsClass_SearchAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchAddress SearchAddressParams { get { return s_params_SearchAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchAddress
        {
            public readonly string id = "id";
            public readonly string page = "page";
            public readonly string pagelimit = "pagelimit";
        }
        static readonly ActionParamsClass_GetAddress s_params_GetAddress = new ActionParamsClass_GetAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAddress GetAddressParams { get { return s_params_GetAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAddress
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateAddressCoords s_params_UpdateAddressCoords = new ActionParamsClass_UpdateAddressCoords();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateAddressCoords UpdateAddressCoordsParams { get { return s_params_UpdateAddressCoords; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateAddressCoords
        {
            public readonly string mode = "mode";
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GridViewPartial = "GridViewPartial";
                public readonly string Index = "Index";
                public readonly string SelectorGridViewPartial = "SelectorGridViewPartial";
            }
            public readonly string GridViewPartial = "~/Areas/WMS/Views/Addresses/GridViewPartial.cshtml";
            public readonly string Index = "~/Areas/WMS/Views/Addresses/Index.cshtml";
            public readonly string SelectorGridViewPartial = "~/Areas/WMS/Views/Addresses/SelectorGridViewPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AddressesController : livemenu.Areas.WMS.Controllers.AddressesController
    {
        public T4MVC_AddressesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SelectorGridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelectorGridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelectorGridViewPartial);
            SelectorGridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ImportOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.JsonResult Import(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Import);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ImportOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void ExportToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportTo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportTo);
            ExportToOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewPartial()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
            GridViewPartialOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<Address, int> updateValues);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<Address, int> updateValues)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            GridViewBatchUpdatePartialOverride(callInfo, updateValues);
            return callInfo;
        }

        [NonAction]
        partial void SearchAddressOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id, int page, int pagelimit);

        [NonAction]
        public override System.Web.Mvc.JsonResult SearchAddress(string id, int page, int pagelimit)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pagelimit", pagelimit);
            SearchAddressOverride(callInfo, id, page, pagelimit);
            return callInfo;
        }

        [NonAction]
        partial void GetAddressOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetAddress(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAddressOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateAddressCoordsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? mode, long? id);

        [NonAction]
        public override System.Web.Mvc.JsonResult UpdateAddressCoords(int? mode, long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateAddressCoords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UpdateAddressCoordsOverride(callInfo, mode, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
