// <auto-generated /> 
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC
 
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace livemenu.Areas.WMS.Controllers
{
    public partial class AvailabilityController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AvailabilityController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GridViewBatchUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StoragePriceListElementGridViewUpdatePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoragePriceListElementGridViewUpdatePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StoragePriceListElementGridViewDeletePartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoragePriceListElementGridViewDeletePartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddPriceListElements()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPriceListElements);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AvailabilityController Actions { get { return MVC.WMS.Availability; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "WMS";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Availability";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Availability";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GridViewPartial = "GridViewPartial";
            public readonly string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public readonly string StoragePriceListElementGridViewUpdatePartial = "StoragePriceListElementGridViewUpdatePartial";
            public readonly string StoragePriceListElementGridViewDeletePartial = "StoragePriceListElementGridViewDeletePartial";
            public readonly string AddPriceListElements = "AddPriceListElements";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GridViewPartial = "GridViewPartial";
            public const string GridViewBatchUpdatePartial = "GridViewBatchUpdatePartial";
            public const string StoragePriceListElementGridViewUpdatePartial = "StoragePriceListElementGridViewUpdatePartial";
            public const string StoragePriceListElementGridViewDeletePartial = "StoragePriceListElementGridViewDeletePartial";
            public const string AddPriceListElements = "AddPriceListElements";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string storageID = "storageID";
        }
        static readonly ActionParamsClass_GridViewPartial s_params_GridViewPartial = new ActionParamsClass_GridViewPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewPartial GridViewPartialParams { get { return s_params_GridViewPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewPartial
        {
            public readonly string storageID = "storageID";
        }
        static readonly ActionParamsClass_GridViewBatchUpdatePartial s_params_GridViewBatchUpdatePartial = new ActionParamsClass_GridViewBatchUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GridViewBatchUpdatePartial GridViewBatchUpdatePartialParams { get { return s_params_GridViewBatchUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GridViewBatchUpdatePartial
        {
            public readonly string updateValues = "updateValues";
            public readonly string storageID = "storageID";
        }
        static readonly ActionParamsClass_StoragePriceListElementGridViewUpdatePartial s_params_StoragePriceListElementGridViewUpdatePartial = new ActionParamsClass_StoragePriceListElementGridViewUpdatePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StoragePriceListElementGridViewUpdatePartial StoragePriceListElementGridViewUpdatePartialParams { get { return s_params_StoragePriceListElementGridViewUpdatePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StoragePriceListElementGridViewUpdatePartial
        {
            public readonly string storagePriceListElement = "storagePriceListElement";
        }
        static readonly ActionParamsClass_StoragePriceListElementGridViewDeletePartial s_params_StoragePriceListElementGridViewDeletePartial = new ActionParamsClass_StoragePriceListElementGridViewDeletePartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StoragePriceListElementGridViewDeletePartial StoragePriceListElementGridViewDeletePartialParams { get { return s_params_StoragePriceListElementGridViewDeletePartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StoragePriceListElementGridViewDeletePartial
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddPriceListElements s_params_AddPriceListElements = new ActionParamsClass_AddPriceListElements();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddPriceListElements AddPriceListElementsParams { get { return s_params_AddPriceListElements; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddPriceListElements
        {
            public readonly string data = "data";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GridViewPartial = "GridViewPartial";
                public readonly string Index = "Index";
            }
            public readonly string GridViewPartial = "~/Areas/WMS/Views/Availability/GridViewPartial.cshtml";
            public readonly string Index = "~/Areas/WMS/Views/Availability/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AvailabilityController : livemenu.Areas.WMS.Controllers.AvailabilityController
    {
        public T4MVC_AvailabilityController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? storageID);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(long? storageID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "storageID", storageID);
            IndexOverride(callInfo, storageID);
            return callInfo;
        }

        [NonAction]
        partial void GridViewPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? storageID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewPartial(long? storageID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "storageID", storageID);
            GridViewPartialOverride(callInfo, storageID);
            return callInfo;
        }

        [NonAction]
        partial void GridViewBatchUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MVCxGridViewBatchUpdateValues<StorageAvailability, int> updateValues, long? storageID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GridViewBatchUpdatePartial(MVCxGridViewBatchUpdateValues<StorageAvailability, int> updateValues, long? storageID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GridViewBatchUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "updateValues", updateValues);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "storageID", storageID);
            GridViewBatchUpdatePartialOverride(callInfo, updateValues, storageID);
            return callInfo;
        }

        [NonAction]
        partial void StoragePriceListElementGridViewUpdatePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, StoragePriceListElement storagePriceListElement);

        [NonAction]
        public override System.Web.Mvc.ActionResult StoragePriceListElementGridViewUpdatePartial(StoragePriceListElement storagePriceListElement)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoragePriceListElementGridViewUpdatePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "storagePriceListElement", storagePriceListElement);
            StoragePriceListElementGridViewUpdatePartialOverride(callInfo, storagePriceListElement);
            return callInfo;
        }

        [NonAction]
        partial void StoragePriceListElementGridViewDeletePartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult StoragePriceListElementGridViewDeletePartial(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoragePriceListElementGridViewDeletePartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            StoragePriceListElementGridViewDeletePartialOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddPriceListElementsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, livemenu.Areas.WMS.Controllers.AvailabilityController.AddStoragePriceListElementsModel data);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddPriceListElements(livemenu.Areas.WMS.Controllers.AvailabilityController.AddStoragePriceListElementsModel data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPriceListElements);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            AddPriceListElementsOverride(callInfo, data);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
